---

- set_fact:
  args:
    sf_apache_vhosts:
      - servername: "{{ item.fqdn }}"
        documentroot: "/var/www/vhosts/{{ item.fqdn }}"
        email: "{{ item.mail | default(meta_vh_default_mail) }}"
  with_items: "{{ meta_vh_hosts }}"
  register: r_apache_vhosts

- set_fact:
    apache_vhosts: "{{ r_apache_vhosts.results | map(attribute='ansible_facts.sf_apache_vhosts.0') | list }}"

- debug: var=apache_vhosts verbosity=1

- set_fact:
  args:
    sf_apache_vhosts_ssl:
      - servername: "{{ item.fqdn }}"
        documentroot: "/var/www/vhosts/{{ item.fqdn }}"
        certificate_file: "{{ item.certificate_file | default('/etc/ssl/certs/mage-snakeoil.pem') }}"
        certificate_key_file: "{{ item.certificate_file | default('/etc/ssl/private/mage-snakeoil.key') }}"
        email: "{{ item.mail | default(meta_vh_default_mail) }}"
  with_items: "{{ meta_vh_hosts }}"
  register: r_apache_vhosts_ssl

- set_fact:
    apache_vhosts_ssl: "{{ r_apache_vhosts_ssl.results | map(attribute='ansible_facts.sf_apache_vhosts_ssl.0') | list }}"

- debug: var=apache_vhosts_ssl verbosity=1
